dist: bionic
language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - libgoogle-glog-dev

git:
  depth: 3

before_install:
  - export wd=$PWD

    # g++ v10
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt install gcc-10 g++-10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100 --slave /usr/bin/gcc gcc /usr/bin/gcc-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10

    # Catch2
#  - sudo git clone https://github.com/microsoft/vcpkg
#  - sudo chown -R $eval$(whoami):$eval$(whoami) vcpkg
#  - cd vcpkg
#  - ./bootstrap-vcpkg.sh
#  - ./vcpkg install catch2
  - git clone -b v2.x https://github.com/catchorg/Catch2.git
  - cd Catch2
  - cmake -Bbuild -H. -DBUILD_TESTING=OFF
  - sudo cmake --build build --target install
  - cd ..

  - cd $wd

script:
  - cmake -H. -Bbuild
  - cmake --build build --target Concurrent
  - cmake --build build --target Test
  - ./build/Test
#  - ./build/Concurrent