name: Concurrent
on: [push, pull_request]
jobs:
  dependencies:
    runs-on:  ubuntu-latest
    steps:
      - name: install threads library
        run: echo "TODO install dependencies here"

  setup:
    needs:    dependencies
    runs-on:  ubuntu-latest
    steps:
      - name: configure cmake
        run:  cmake -H. -Bbuild

  build:
    needs:    setup
    runs-on:  ubuntu-latest
    steps:
      - name: Build src and lib files
        run:  cmake --build build --target Concurrent

  build-tests:
    needs:    build
    runs-on:  ubuntu-latest
    steps:
      - name: Build test files
        run:  cmake --build build --target Test

  tests:
    needs:    build-tests
    runs-on:  ubuntu-latest
    steps:
      - name: Run the tests
        run: ./build/Test

  benchmarks:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Run the benchmarks
        run: ./build/Concurrent

  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Do a task that has to be successful
        run: echo "Hello World"
