name: Concurrent
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        run: cmake -H. -Bbuild
      - name: Build the tests
        run: cmake --build build --target Test
      - name: Run the tests
        run: ./build/Test
  run-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        run: cmake -H. -Bbuild
      - name: Build the project
        run: cmake --build build --target Concurrent
      - name: Run the benchmarks
        run: ./build/Concurrent
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Do a task that has to be successful
        run: echo "Hello World"
