name: Concurrent
on: [push, pull_request]
jobs:
  dependencies:
    needs: catch2
    runs-on:  ubuntu-latest
    steps:
      - name: install cmake
        run:  sudo apt install cmake
      - name: install g++-10
        run:  sudo apt install g++-10
      - name: install threads library
        run:  sudo apt install libpthread-stubs0-dev
      - name: install google logging library
        run:  libgoogle-glog-dev

  catch2:
    runs-on:  ubuntu-latest
    steps:
      - name: install catch2
        run: echo "TODO"

  setup:
    needs:    dependencies
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure cmake
        run:  cmake -H. -Bbuild

  build:
    needs:    setup
    runs-on:  ubuntu-latest
    steps:
      - name: Build src and lib files
        run:  cmake --build build --target Concurrent

  build-tests:
    needs:    build
    runs-on:  ubuntu-latest
    steps:
      - name: Build test files
        run:  cmake --build build --target Test

  tests:
    needs:    build-tests
    runs-on:  ubuntu-latest
    steps:
      - name: Run the tests
        run: ./build/Test

  benchmarks:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Run the benchmarks
        run: ./build/Concurrent

  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Do a task that has to be successful
      - run: echo "Hello World"
