name: Concurrent
on: [push, pull_request]
jobs:
  dependencies:
    runs-on:  ubuntu-latest
    steps:
      - name: install cmake
        run:  sudo apt install cmake
      - name: install g++-10
        run:  sudo apt install g++-10
      - name: install threads library
        run:  sudo apt install libpthread-stubs0-dev
      - name: install google logging library
        run:  sudo apt install libgoogle-glog-dev
      - name: download catch2 v2
        run:  git clone -b v2.x https://github.com/catchorg/Catch2.git
      - name: setup catch2
        run:  cmake -BCatch2/build -HCatch2 -DBUILD_TESTING=OFF
      - name: build and install catch2
        run: sudo cmake --build Catch2/build --target install

  build:
    needs:    dependencies
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure cmake
        run:  cmake -H. -Bbuild
      - name: Build src and lib files
        run:  cmake --build build --target Concurrent

  build-tests:
    needs:    build
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure cmake
        run:  cmake -H. -Bbuild
      - name: Build test files
        run:  cmake --build build --target Test

  tests:
    needs:    build-tests
    runs-on:  ubuntu-latest
    steps:
      - name: Run the tests
        run: ./build/Test

  benchmarks:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Run the benchmarks
        run: ./build/Concurrent

  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Do a task that has to be successful
        run: echo "Hello World"
